### ISSUE TITLE
Skill response was marked as failure

### ISSUE THREAD

**Issue by woodnt** [tartanguru/alexa-assistant-instructions#12]
Hello,

I have finished and linked my install. 

When I try to invoke, I get the below:

Skill response was marked as failure
Google Assistant for Alexa
Request Identifier: amzn1.echo-api.request.663babf8-176f-4431-aaf3-a60e4609e0aa

The target Lambda application returned a failure response.

If I need to post logs, can you please tell me how?

Thank you for your work on this project and willingness to help its install.

Kindly,
Nathan

**Comment by Goldbricker** [comment]
Hey, I'm getting this same issue too. It looks like the Alexa Skills Kit Development site has gone through some changes since the instructions were written and I don't know if that is related.

For example, the structure of the json has changed,
[AlexaGoogleNewJson.txt](https://github.com/tartanguru/alexa-assistant-instructions/files/1858319/AlexaGoogleNewJson.txt)

The "Render Template" option doesn't exist, it looks like it is now called "Display Interface"

Setting up the Intent and the Slot Type was a little different too so I may have got it wrong.

When you run it in the test harness the Initialisation works it says "welcome to Google how can I help" but when you type a follow up response you get the failure response.

Can you explain exactly which logs you need?

**Comment by Goldbricker** [comment]
Actually just after I wrote this I got it working by changing the Intent Slot name to lowercase "search". If you want some screenshots from the new Alexa Skills Kit Development site I can attach them.

**Comment by ilavender** [comment]
@Goldbricker can you please post the updated JSON?
10x

**Comment by tartanguru** [comment]
Closing this issue as #13 is tracking this issue

**Comment by gdkali** [comment]
> Actually just after I wrote this I got it working by changing the Intent Slot name to lowercase "search". If you want some screenshots from the new Alexa Skills Kit Development site I can attach them.

please attach screenshot
