### ISSUE TITLE
There was a Problem with Requested Skills Response

### ISSUE THREAD

**Issue by ilavender** [tartanguru/alexa-assistant-instructions#15]
the template generator is gone so please post the json as I'm not sure if the problem is within the skill or the Lambda function

**Comment by tartanguru** [comment]
Closing as this is a duplicate of issue 12

**Comment by ilavender** [comment]
well, I'm not sure it's the same case as the nodejs shows another exception:

```
2018-04-10T21:27:19.896Z	f28ae686-3d05-11e8-8b43-4746d366a61c	TypeError: Cannot read property '0' of undefined
at Response.<anonymous> (/var/task/index.js:95:60)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
END RequestId: f28ae686-3d05-11e8-8b43-4746d366a61c
REPORT RequestId: f28ae686-3d05-11e8-8b43-4746d366a61c	Duration: 112.49 ms	Billed Duration: 200 ms Memory Size: 1344 MB	Max Memory Used: 75 MB	
RequestId: f28ae686-3d05-11e8-8b43-4746d366a61c Process exited before completing request
```

**Comment by tartanguru** [comment]
Ok - couple of things here.

1 - What is the actual issue here as the title of the issue is regarding an invalid skill response whist the body of the issue describes the change to the skill setup pages?
2. If this actually about the skill failing then you’ve raised this in the wrong project - this is project is merely a set of installation instructions. You should raise issue about the code in the skilll project
3. A log without any context isn’t really much use. Is this from the first time you called the skill? Have you managed to link it? What command are you using to create this error

**Comment by tartanguru** [comment]
Here’s a guide on how to raise an effective github issue:- 

https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/

**Comment by ilavender** [comment]
@tartanguru I think I know how to raise an issue... just wasn't sure if the issue is result of me missing steps from the instructions or problem within the nodejs. maybe it's related to the fact that you have this separate repository for instructions and the actual app.

Here's a guide on effective github documentation for projects.
https://blog.github.com/2016-08-22-publish-your-project-documentation-with-github-pages/

**Comment by tartanguru** [comment]
Well I’ve merely asked you for the additional information that would normally be required to diagnose an issue. There really is no need to start posting passive aggressive message when I have taken time out of my day to try an help you out.

I’ve spent hundreds of hours of my time developing these skills and I quite frankly don’t appreciate the attitude.

**Comment by ilavender** [comment]
your work is highly appreciated. seriously, this is great project and very
nice of you to share it.
having that said, you could just answer the first question posting the json
so I could verify my configuration before declaring a real issue...
posting a guide on how to raise an issue on github was unnecessary and
conical.

**Comment by ilavender** [comment]
1 - The actual issue here - this is the error alexa say "There was a Problem with Requested Skills Response"
2. raise issue about the code in the skilll project - I don't know that it's related to the nodejs or my configuration, I will post the JSON here...
3. this is from the first time calling the skill. Yes, it is linked. What command are you using to create this error: "alexa, open google" or "alexa, ask google what is the time"

**Comment by ilavender** [comment]
Here's the JSON:
```
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "google",
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.MoreIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateSettingsIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NextIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NoIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PreviousIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollLeftIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollRightIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.YesIntent",
                    "samples": []
                },
                {
                    "name": "SearchIntent",
                    "slots": [
                        {
                            "name": "search",
                            "type": "SEARCH"
                        }
                    ],
                    "samples": [
                        "{search}"
                    ]
                }
            ],
            "types": [
                {
                    "name": "SEARCH",
                    "values": [
                        {
                            "name": {
                                "value": "who is the queen"
                            }
                        },
                        {
                            "name": {
                                "value": "why is the sky blue"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

**Comment by ilavender** [comment]
was resolved by placing the correct client_secret.json

**Comment by tartanguru** [comment]
Since Amazon changed the layout of the Alexa developer site, the existing JSON does not work. I had previously not yet tried the new site and my project was deployed using the old site so I didn't have the new JSON format and this is why I linked to issue #13 which contains a user submitted JSON which is known to work. This is why I originally closed the issue and linked to the other one as this met the needs of your original request.

I have however just exported the JSON from my developer console as the project has been automatically migrated to the new layout below which by eye looks the same as yours

`{
    "interactionModel": {
        "languageModel": {
            "invocationName": "google",
            "intents": [
                {
                    "name": "AMAZON.NavigateSettingsIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.MoreIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollRightIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollLeftIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NextIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PreviousIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "SearchIntent",
                    "slots": [
                        {
                            "name": "search",
                            "type": "SEARCH"
                        }
                    ],
                    "samples": [
                        "{search}"
                    ]
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "SEARCH",
                    "values": [
                        {
                            "name": {
                                "value": "who is the queen"
                            }
                        },
                        {
                            "name": {
                                "value": "why is the sky blue"
                            }
                        }
                    ]
                }
            ]
        }
    }
}`

This would imply that the issue is not related to the interaction model.

Second issue is as to why the lambda code had failed. This is likely to be a config issue rather than code issue as there have been over 8000 deploys from the cloudformation template and this is the first time this has arisen although I can't rule out a code issue completely. In order to work this out I need more than just the logs and need some context which is why I linked to the guide regarding raising issues so that you could get a feel for what is required. Now that I have that context I believe I know what the issue is
From the logs, it seems to be having as issue reading the client.secret.json file. The error suggests that it isn't finding a redirect_uris object array containing all of the redirect_uri's. I would suggest double checking in the Google API console as to whether you have added ALL of the re-direct URI's that are listed in the Lambda authentication tab as the skill expects there to be more than one which might be the problem if you have only entered one.
I suspect that you must have at least one presenting the client_secret.json file otherwise you wouldn't have been able to link the skill.
I'll try and add an additional check to the code for the next release to try and catch this error

**Comment by tartanguru** [comment]
Looks like my suspicions were correct then regarding the client_secret.json file. I will try and modify the code to do some more checking on the config

**Comment by tartanguru** [comment]
Looks like my suspicions were correct then regarding the client_secret.json file. I will try and modify the code to do some more checking on the config
