### ISSUE TITLE
google assistant launchs, but dont answer.

### ISSUE THREAD

**Issue by markusAT** [tartanguru/alexa-assistant-instructions#8]
Hello!

Alexa launches the google assistant and when i ask something alexa responds  in english with "i am not sure what you said please repeat" every time

Google Assistant launchs in german thats fine.

Did I missed something in the tutorial?

**Comment by tartanguru** [comment]
Make sure you have added English as a language to the skill

**Comment by markusAT** [comment]
so i added german and now english.
need to config every thing in english?
(i use alexa in german)

**Comment by tartanguru** [comment]
Ah ok - sorry I now understand what your issue is - you don’t need to add
English to the skill
Have you set the language setting to German in the Google Assistant app on
your phone?
Otherwise it will be expecting to recieve English and obviously you will be
speaking German - that it’s why she says she doesn’t understand!

**Comment by markusAT** [comment]
I have found the problem.
I messed up with Thema intents anderen the New Website Design.

Now everything works!

Thank you for the fast response and good work!

**Comment by markusAT** [comment]
* i messed up with the intents and the new Website Design
